apiVersion: 1

datasources:
- name: 'Prometheus'
  type: 'prometheus'
  access: 'browser'
  url: 'http://localhost:9090'
  is_default: true
  editable: false

- name: InfluxDB
  type: influxdb
  access: proxy
  database: db0
  user: admin
  password: admin
  url: http://influxdb:8086
  isDefault: true
  editable: true